In [18]:
"""
1. Neural Network and Activation Function
"""

'\n1. Neural Network and Activation Function\n'

In [19]:
import torch
from torch import nn
# linear = nn.Linear(in_features, out_features)
linear = nn.Linear(32,2)
inputs = torch.rand(3,32)
outputs = linear(inputs)
print(outputs)

tensor([[ 0.0333,  0.3738],
        [ 0.0583,  0.3696],
        [-0.0028,  0.4307]], grad_fn=<AddmmBackward0>)


In [20]:
from torch.nn import functional as F
activation  = F.sigmoid(outputs)
print(activation)

tensor([[0.5083, 0.5924],
        [0.5146, 0.5914],
        [0.4993, 0.6061]], grad_fn=<SigmoidBackward0>)


D:\Program Files\anaconda3\lib\site-packages\torch\nn\functional.py:1806: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


In [21]:
activation = F.softmax(outputs, dim=1)
print(activation)

tensor([[0.4157, 0.5843],
        [0.4228, 0.5772],
        [0.3933, 0.6067]], grad_fn=<SoftmaxBackward0>)


In [22]:
activation = F.relu(outputs)
print(activation)

tensor([[0.0333, 0.3738],
        [0.0583, 0.3696],
        [0.0000, 0.4307]], grad_fn=<ReluBackward0>)


In [23]:
"""
2. Constumed Neural Network Model
"""

import torch
from torch import nn
from torch.nn import functional as F

"""
Key: (1) Evlate a subclass from class Module of torch.nn
     (2) access constructor & forward

"""


class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_class):
        super(MLP, self).__init__() # linear transformation
        self.linear1 = nn.Linear(input_dim, hidden_dim)
        self.activate = F.relu
        self.linear2 = nn.Linear(hidden_dim, num_class)
    def forward(self, inputs):
        hidden = self.linear1(inputs)
        activation = self.activate(hidden)
        outputs = self.linear2(activation)
        probs = F.softmax(outputs,dim=1)
        return probs
mlp = MLP(input_dim=4,hidden_dim=5, num_class= 2)
inputs = torch.rand(3,4)
probs = mlp(inputs)
print(probs)

tensor([[0.2369, 0.7631],
        [0.3061, 0.6939],
        [0.2948, 0.7052]], grad_fn=<SoftmaxBackward0>)
