In [5]:
import torch
from torch.nn import  RNN
rnn = RNN(input_size=4, hidden_size=5, batch_first=True)
inputs = torch.rand(2,3,4)
outputs, hn = rnn(inputs)
# outputs: hidden layer of output series
# hn: hidden layer in the last time
print(outputs)
print(hn)
print(outputs.shape,hn.shape)

# other parameters:
# bidrirectional = True (False by default)
# num_layers = 1 (1 by default)

tensor([[[ 0.5193,  0.4672, -0.2160,  0.2449, -0.0979],
         [ 0.4692,  0.3137, -0.0300, -0.3287,  0.2089],
         [ 0.6854,  0.2792, -0.2220, -0.3778,  0.2201]],

        [[ 0.5436,  0.2994, -0.5330,  0.1497, -0.1878],
         [ 0.5023,  0.5380,  0.0657, -0.1530,  0.0236],
         [ 0.5890,  0.1331, -0.0687, -0.3336,  0.1587]]],
       grad_fn=<TransposeBackward1>)
tensor([[[ 0.6854,  0.2792, -0.2220, -0.3778,  0.2201],
         [ 0.5890,  0.1331, -0.0687, -0.3336,  0.1587]]],
       grad_fn=<StackBackward0>)
torch.Size([2, 3, 5]) torch.Size([1, 2, 5])


In [6]:
from torch.nn import  LSTM
lstm = LSTM(input_size=4,hidden_size=5,batch_first=True)
inputs = torch.rand(2,3,4)
outputs, (hn, cn) = lstm(inputs)
print(outputs)
print(hn)
print(cn)
print(outputs.shape,hn.shape,cn.shape)

tensor([[[ 0.2344,  0.0873, -0.0575,  0.0427,  0.0387],
         [ 0.3352,  0.1491, -0.1493,  0.1126,  0.0304],
         [ 0.4318,  0.2487, -0.1345,  0.0267,  0.0334]],

        [[ 0.1709,  0.0844, -0.1193,  0.1348, -0.0202],
         [ 0.3931,  0.2335, -0.1581,  0.0752,  0.0126],
         [ 0.3846,  0.2303, -0.1127,  0.0503, -0.0484]]],
       grad_fn=<TransposeBackward0>)
tensor([[[ 0.4318,  0.2487, -0.1345,  0.0267,  0.0334],
         [ 0.3846,  0.2303, -0.1127,  0.0503, -0.0484]]],
       grad_fn=<StackBackward0>)
tensor([[[ 0.7176,  0.3356, -0.2720,  0.0365,  0.0726],
         [ 0.6858,  0.3352, -0.2023,  0.0772, -0.0854]]],
       grad_fn=<StackBackward0>)
torch.Size([2, 3, 5]) torch.Size([1, 2, 5]) torch.Size([1, 2, 5])
