In [28]:
"""
Convolutional Layer
"""
import torch
from  torch.nn import  Conv1d
conv1 = Conv1d(5,2,4)
# input_channel=5, output_channel=2, kernel_size=4
conv2 = Conv1d(5,2,3)
inputs = torch.rand(2,5,6)
outputs1 = conv1(inputs)
outputs2 = conv2(inputs)
# print(outputs1)
# print(outputs2)

In [29]:
"""
2. MaxPool Layer
"""

"""
Maxpooling Operation by explicitly defining an item
"""
import  torch
from torch.nn import MaxPool1d
pool1 = MaxPool1d(3)
# pool_kernel_size=3,
# length of output series of convolutional layer = 3
pool2 = MaxPool1d(4)
# pool_kernel_size=4
outputs_pool1 = pool1(outputs1)
# 1-D max pool, get max of every row input
outputs_pool2 = pool2(outputs2)
print(outputs1)
print(outputs2)

print(outputs_pool1)
print(outputs_pool2)

tensor([[[ 0.1471,  0.0776,  0.1905],
         [-0.6662, -0.8031, -0.5298]],

        [[ 0.1253, -0.0064, -0.0161],
         [-0.5658, -0.6812, -0.4566]]], grad_fn=<SqueezeBackward1>)
tensor([[[-0.1302,  0.1459, -0.1936, -0.2998],
         [-0.7205,  0.1708, -0.4805, -0.2587]],

        [[ 0.0113, -0.2126, -0.1101, -0.0383],
         [-0.4307, -0.2267, -0.4065, -0.2733]]], grad_fn=<SqueezeBackward1>)
tensor([[[ 0.1905],
         [-0.5298]],

        [[ 0.1253],
         [-0.4566]]], grad_fn=<SqueezeBackward1>)
tensor([[[ 0.1459],
         [ 0.1708]],

        [[ 0.0113],
         [-0.2267]]], grad_fn=<SqueezeBackward1>)


In [30]:
"""
Maxpooling Operation by calling function
"""
import torch.nn.functional as F
outputs_pool1 = F.max_pool1d(outputs1,kernel_size=outputs1.shape[2])
# last dimision of outputs1 is the length of series
# print(outputs1.shape)
print(outputs1)

tensor([[[ 0.1471,  0.0776,  0.1905],
         [-0.6662, -0.8031, -0.5298]],

        [[ 0.1253, -0.0064, -0.0161],
         [-0.5658, -0.6812, -0.4566]]], grad_fn=<SqueezeBackward1>)


In [31]:
outputs_pool1_squeeze1 = outputs_pool1.squeeze(dim=2)
print(outputs_pool1_squeeze1)
outputs_pool2_squeeze2 = outputs_pool2.squeeze(dim=2)
print(outputs_pool2_squeeze2)
outpus_pool = torch.cat([outputs_pool1_squeeze1,outputs_pool2_squeeze2])
print(outpus_pool)

tensor([[ 0.1905, -0.5298],
        [ 0.1253, -0.4566]], grad_fn=<SqueezeBackward1>)
tensor([[ 0.1459,  0.1708],
        [ 0.0113, -0.2267]], grad_fn=<SqueezeBackward1>)
tensor([[ 0.1905, -0.5298],
        [ 0.1253, -0.4566],
        [ 0.1459,  0.1708],
        [ 0.0113, -0.2267]], grad_fn=<CatBackward0>)
